version: '3'
services:
  frontapp:
    build:
      context: ./frontapp
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgis://volodymyr:volodymyr@db:5432/cropio_development
      - RAILS_MASTER_KEY=cab8bab460ce59f3b039b80a92d0323e
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgis/postgis:14-3.4
    restart: "no"
    environment:
      POSTGRES_USER: volodymyr
      POSTGRES_PASSWORD: volodymyr
      POSTGRES_DB: cropio_development
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: data-postgis14-data
